[package]
name = "rust_os"
version = "0.1.0"
authors = ["jmill"]
edition = "2018"

# used for `cargo build`
[profile.dev]
panic = "abort"  # disable stack unwinding on panic

# used for `cargo build --release`
[profile.release]
panic = "abort"  # disable stack unwinding on panic
